### ISSUE TITLE
建议，不要用是或否，而是列表

### ISSUE THREAD

**Issue by tioover** [ling0322/webdict#2]
人选东西有惯性的，如果一直都不是一个词可能会漏掉，或许可以给出多个候选的词语的列表，然后让人选哪些是一个词语，提交了再下一组，这样不容易选错，而且错了，只要没提交还可以改。

**Comment by yuikns** [comment]
赞同

**Comment by ling0322** [comment]
这个方案我想过，但是感觉操作太复杂了，用户体验可能会不怎么好。为了判断一组N个词语需要精确移动N次鼠标，点击N+1次；相反一个一个词语显示的时候，只需要大致的移动一下(按钮比较大)以及点击一下就可以了。不过咱正在准备解决选错撤销的问题。

**Comment by tioover** [comment]
@ling0322 只要列表上的项可点击区域足够大就好了，如果一组列表只有四五个词的话就可以做的很大，有效消除恐慌感。

**Comment by ansjsun** [comment]
建议后期有对词分类的功能。。还有我也想加入这个项目

**Comment by ling0322** [comment]
词语分类的话CRF POS Tagging的模型已经准备OK了

**Comment by ansjsun** [comment]
是否可以用键盘快捷键来处理。或者鼠标左右键。现在每次判断都需要移动鼠标。。。我看了下词库。词量还是比较少的。我这里有一些辞典 。是否能合并进去。。还有没有词性或者词性不统一很麻烦。。因为我之前都是用北大的标注。可能和你用斯坦福不太一致。这是后话了

**Comment by ling0322** [comment]
其实快捷键是有的T就是一个词，F就是不是一个词。另外尝试过列表模式，但是各种不和谐感就放弃了。谢谢支持:-)
